### ISSUE TITLE
Unresolved cref causes unclear build error

### ISSUE THREAD

**Issue by coreyshuman** [saucecontrol/InheritDoc#17]
If an inheritdoc cref (on a class) cannot be resolved, it causes a "Length cannot be less than zero." error and fails the build. This is difficult to troubleshoot. A more specific error message or a warning without failing the build could be more user-friendly.

Here is the exact error message:

```
Length cannot be less than zero.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at InheritDocProcessor.getTypeIDFromDocID(String docID)
   at InheritDocProcessor.<>c__DisplayClass6_0.<InheritDocs>b__9(String c)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
   at System.Collections.Generic.HashSet`1..ctor(IEnumerable`1 collection, IEqualityComparer`1 comparer)
   at InheritDocProcessor.InheritDocs(String asmPath, String docPath, String outPath, String[] refPaths, String[] addPaths, ApiLevel trimLevel, ILogger logger)
   at InheritDocTask.Execute()
```

It looks like the error occurs on this line, when `getTypeIDFromDocID()` is called: 
https://github.com/saucecontrol/InheritDoc/blob/44650b707637e70b98adb192b6b8bccca7adf241/src/InheritDoc/InheritDocProcessor.cs#L100

A simple way to recreate the issue is to add an inheritdoc tag with an empty cref like this:

```
/// <inheritdoc cref="" />
public class ...
```

Please let me know if have any questions. If I can carve out some time, I'll try to come up with a fix for this.
Thanks for this great software tool, it's helped me out a ton!

**Comment by saucecontrol** [comment]
Nice catch, thanks!  I've pushed a fix in https://github.com/saucecontrol/InheritDoc/commit/9e66e348d6a5dc4557777eb1311ef678601b5654.

You'll now get an `IDT002` warning referencing the malformed cref (Roslyn prefixes unresolved crefs with `!:`), but you should be getting more explicit C# warnings before that.

I'll publish a new release shortly.

**Comment by coreyshuman** [comment]
Right on, thank you! This worked perfectly for me.
